<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ua [
<!ELEMENT config (account, uaserver, rtpaudio, regproxy, log, audio)>
<!ELEMENT account EMPTY>
<!ATTLIST account username CDATA #REQUIRED>
<!ATTLIST account passwd CDATA #IMPLIED>
<!ELEMENT uaserver EMPTY>
<!ATTLIST uaserver ip CDATA #IMPLIED>
<!ATTLIST uaserver puerto CDATA #REQUIRED>
<!ELEMENT rtpaudio EMPTY>
<!ATTLIST rtpaudio puerto CDATA #REQUIRED>
<!ELEMENT regproxy EMPTY>
<!ATTLIST regproxy ip CDATA #REQUIRED>
<!ATTLIST regproxy puerto CDATA #REQUIRED>
<!ELEMENT log EMPTY>
<!ATTLIST log path CDATA #REQUIRED>
<!ELEMENT audio EMPTY>
<!ATTLIST audio path CDATA #REQUIRED>
]>

<ua>
  <account username="miriam@urjc.es" passwd=""></account>
  <uaserver ip="127.0.0.1" puerto="9999"></uaserver>
  <rtpaudio puerto="5555"></rtpaudio>
  <regproxy ip="127.0.0.1" puerto="6666"></regproxy>
  <log path="fichlogua1.txt"></log>
  <audio path="cancion.mp3"></audio>
</ua>
